apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-rich
  labels:
    app:  web-rich
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  web-rich
  template:
    metadata:
      labels:
        app:  web-rich
    spec:
      containers:
        - name:  web-rich-pod
          image: nginx:latest
          ports:
            - containerPort: 80