name: "Terraform CI/CD"
on:
  push:
    branches: ["main"]     # Триггер на изменения в main
  pull_request:            # Триггер на PR в любую ветку

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest
    environment: production  # Для ручного подтверждения (опционально)
    defaults:
      run:
        working-directory: ./terraform  # Путь к Terraform-коду

    steps:
      # 1. Checkout кода
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Установка Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"  # Укажите нужную версию

      # 3. Инициализация Terraform (с AWS credentials)
      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init

      # 4. Проверка форматирования
      - name: Terraform Format Check
        run: terraform fmt -check

      # 5. Проверка валидности конфига
      - name: Terraform Validate
        run: terraform validate

      # 6. Запуск Plan (для PR и push)
      - name: Terraform Plan
        run: terraform plan -input=false
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'

      # 7. Запуск Apply (только для main)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
